project:
  type: website
  output-dir: ../docs/ca
  resources:
    - "../data/*"
    - "../en/images/*"

website:
  title: "Atles Electoral · Segona República"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: "Inici"
      - href: map.qmd
        text: "Mapa"
      - href: codebook.qmd
        text: "Dades"
      - href: methods.qmd
        text: "Mètodes"
      - href: contribute.qmd
        text: "Contribuir"
      - href: about.qmd
        text: "Sobre el projecte"
      - href: book.qmd
        text: "El Llibre"

format:
  html:
    theme: minimal
    css: "styles.css"
    toc: false
    page-layout: full
