project:
  type: website
  output-dir: ../docs/es
  resources:
    - "../data/*"
    - "../en/images/*"

website:
  title: "Atlas Electoral · Segunda República"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: "Inicio"
      - href: map.qmd
        text: "Mapa"
      - href: codebook.qmd
        text: "Datos"
      - href: methods.qmd
        text: "Métodos"
      - href: contribute.qmd
        text: "Contribuir"
      - href: about.qmd
        text: "Sobre el proyecto"
      - href: book.qmd
        text: "El Libro"

format:
  html:
    theme: minimal
    css: "styles.css"
    toc: false
    page-layout: full
